### ISSUE TITLE
app/about-us.html

### ISSUE THREAD

**Issue by borodjuka** [ApeironHTML5Group/quiz#2]
app/about-us.html nije validna html5 stranica, nedostaje html, head, body...
Takođe postoji problem sa encodingom, imena sa našim slovima se ne prikazuju ispravno.

**Comment by ghost** [comment]
Dodani html tagovi da bi stranica bila u skladu sa HTML5 standardom. Popravljen encodin. Trenutno stranica ne prolazi online HTML5 validaciju jer se`<a>`element nalazi u `<figure>` elementu...

Greska je mozda sto sam commit-ovao na master branch?

**Comment by borodjuka** [comment]
Borise ispravio sam ja ovaj fajl. Sada je OK.
